{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "30fd5d98-e922-44ed-91d4-36abe859281e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "qt.qml.typeregistration: Invalid QML element name \"IconCode\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"MusicalSymbolCodes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"ContainerType\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"NavigationEvent\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"MUAccessible\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"CompareType\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"SelectionMode\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"ToolBarItemType\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"DockToolBarAlignment\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"Location\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"CloudVisibility\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"SaveToCloudResponse\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"DirectionTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"SlurTieTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"NoteHead\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"Beam\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"Hairpin\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"OrnamentTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"Dynamic\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"Glissando\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"CommonTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"BarlineTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"MarkerTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"KeySignatureTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"AccidentalTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"FretDiagramTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"LineTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"TextTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"ArticulationTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"AmbitusTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"ChordSymbolTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"BendTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"TremoloBarTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"TremoloTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"VoiceTypes\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"LayoutPanelItemType\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"ShadowNotePopupContent\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"PanelMode\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"StandardButton\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"SaveLocationType\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"GenerateAudioTimePeriodType\"; value type names should begin with a lowercase letter\n",
      "qt.qml.typeregistration: Invalid QML element name \"MigrationType\"; value type names should begin with a lowercase letter\n"
     ]
    }
   ],
   "source": [
    "import subprocess\n",
    "import os\n",
    "import threading\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog, messagebox\n",
    "\n",
    "import json\n",
    "import os\n",
    "\n",
    "CONFIG_FILE = \"config.json\"\n",
    "\n",
    "def load_config():\n",
    "    if os.path.exists(CONFIG_FILE):\n",
    "        with open(CONFIG_FILE) as f:\n",
    "            return json.load(f)\n",
    "    return {}\n",
    "\n",
    "def save_config(config):\n",
    "    with open(CONFIG_FILE, \"w\") as f:\n",
    "        json.dump(config, f)\n",
    "\n",
    "config = load_config()\n",
    "MUSESCORE_PATH = config.get(\"musescore_path\", \"/Applications/MuseScore 4.app/Contents/MacOS/mscore\")\n",
    "\n",
    "def convert_mxl_to_mp3(mxl_path, status_label):\n",
    "    status_label.config(text=\"Converting... Please wait.\")\n",
    "    output_mp3 = os.path.splitext(mxl_path)[0] + \".mp3\"\n",
    "    try:\n",
    "        subprocess.run([MUSESCORE_PATH, \"-o\", output_mp3, mxl_path], check=True)\n",
    "        status_label.config(text=f\"Conversion done! Saved as:\\n{output_mp3}\")\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        status_label.config(text=\"Conversion failed.\")\n",
    "        messagebox.showerror(\"Conversion Error\", str(e))\n",
    "\n",
    "def start_conversion_thread(mxl_path, status_label):\n",
    "    thread = threading.Thread(target=convert_mxl_to_mp3, args=(mxl_path, status_label))\n",
    "    thread.start()\n",
    "\n",
    "def browse_file():\n",
    "    file_path = filedialog.askopenfilename(filetypes=[(\"MusicXML files\", \"*.mxl\"), (\"All files\", \"*.*\")])\n",
    "    if file_path:\n",
    "        entry_path.delete(0, tk.END)\n",
    "        entry_path.insert(0, file_path)\n",
    "        status_label.config(text=\"\")\n",
    "\n",
    "def start_conversion():\n",
    "    mxl_path = entry_path.get()\n",
    "    if not mxl_path:\n",
    "        messagebox.showwarning(\"Input Needed\", \"Please select a .mxl file first.\")\n",
    "        return\n",
    "    start_conversion_thread(mxl_path, status_label)\n",
    "\n",
    "root = tk.Tk()\n",
    "root.title(\"MusicXML to MP3 Converter\")\n",
    "root.geometry(\"450x180\")\n",
    "\n",
    "tk.Label(root, text=\"Select MusicXML (.mxl) file:\").pack(pady=5)\n",
    "entry_path = tk.Entry(root, width=50)\n",
    "entry_path.pack(pady=5)\n",
    "\n",
    "btn_browse = tk.Button(root, text=\"Browse\", command=browse_file)\n",
    "btn_browse.pack(pady=5)\n",
    "\n",
    "btn_convert = tk.Button(root, text=\"Convert to MP3\", command=start_conversion)\n",
    "btn_convert.pack(pady=10)\n",
    "\n",
    "status_label = tk.Label(root, text=\"\", fg=\"blue\")\n",
    "status_label.pack(pady=5)\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67aa0e83-c8c9-4f54-9612-f9ac011d8ec7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
